services:
  backend:
    build: .
    container_name: support-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chroma
    volumes:
      - .:/app

  chroma:
    image: chromadb/chroma
    container_name: support-chroma
    ports:
      - "8001:8000"
    volumes:
      - chromadata:/chroma/.chroma

volumes:
  chromadata:
